[package]
name = "swaylid"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
swayipc = "3.0.1"

[profile.release]
strip=true
lto=true
panic="abort"
