[package]
name = "swaylid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
edid-rs = "0.1.0"
swayipc = "3.0.1"
